stages:
  - build
  - test
  - push

build:
  image: docker:20
  services:
    - docker:dind
  stage: build
  script:
    - docker build -t your-dockerhub-username/backend-app:$CI_COMMIT_SHA ./backend
    - docker build -t your-dockerhub-username/frontend-app:$CI_COMMIT_SHA ./frontend

push:
  stage: push
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push eshamafzal/backend-app:$CI_COMMIT_SHA
    - docker push eshamafzal/frontend-app:$CI_COMMIT_SHA
