

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development

  frontend:
    build:
      context: ./Front-end
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Map port 3000 for frontend
    volumes:
      - ./Front-end:/app
      - /app/node_modules
