version: '3.8'

services:
  frontend:
    build:
      context: ./Front-end
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./Front-end:/app
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production